### ISSUE TITLE
Errors of runing main_spine_localization.py

### ISSUE THREAD

**Issue by zhuo-CHENG** [christianpayer/MedicalDataAugmentationTool-VerSe#1]
Hi, thanks for your open-source toolkit and project. It's very helpful and attractive.
I'm trying to train models of this project. But when I ran the first training file, I met some errors.

This is the information of errors. 
The version of Tensorflow is 1.14 and OS is Ubuntu.

Could you tell me how can I solve this problem?
Thank you very much! 

<img width="578" alt="1" src="https://user-images.githubusercontent.com/56423748/79443177-76429e00-8014-11ea-8cdf-f669d969986d.png">
<img width="571" alt="2" src="https://user-images.githubusercontent.com/56423748/79443183-76db3480-8014-11ea-8607-4f296007840d.png">
![3](https://user-images.githubusercontent.com/56423748/79443887-65def300-8015-11ea-8589-d0392b7232dc.png)

**Comment by christianpayer** [comment]
Hi, thanks for using our code.

I can't reproduce your error and I have never seen a similar error. The training scripts work fine for all of my computers. Also, I think your log is not complete.
By looking at the output, there may be a problem with uninitialized variables. You could check, if they are initialized (this happens in the function initialize_variables in MainLoop). Also, check if every path is set correctly and the images are where they should be.

I cannot tell you anything else. You unfortunately need to debug it on your computer. I still hope that my answer could help you.

**Comment by zhuo-CHENG** [comment]
@christianpayer 
Hi, thanks for your reply and your information.
I would like to try to solve it and update if any progress.
Thank you very much.
