### ISSUE TITLE
Training doesn't start :(

### ISSUE THREAD

**Issue by hanbinko** [christianpayer/MedicalDataAugmentationTool-VerSe#14]
![image](https://user-images.githubusercontent.com/73213302/113546805-af11c380-9627-11eb-8ad4-ceef45f96787.png)

when i start the training the segmentationscript, the execution stops here.. and don't move on..

**Comment by hanbinko** [comment]
Nevermind! Solved the issue

**Comment by dmus** [comment]
I do have the same. Could you say how you solved the issue?

**Comment by dmus** [comment]
Solution for me seems te be loading correct CUDA and cudnn versions. cuda 10.1 for use with tensorflow 2.2
