### ISSUE TITLE
How to generate landmark.csv

### ISSUE THREAD

**Issue by zengchan** [christianpayer/MedicalDataAugmentationTool-VerSe#2]
Thank you very much for your open source code which helps me a lot.  I have a question about the landmark.csv which is a littile different  from the official JSON file. It much confuse me about the X coordinate value and how to generate my own  landmark.csv.

**Comment by christianpayer** [comment]
Hi, I'm glad that the code can help you.
You are right, the csv file contains coordinates in a different system than the json files.
The original coordinates system is described in https://verse2019.grand-challenge.org/Data/.
Our framework however, uses a different coordinate system for landmark annotations. We mainly use physical coordinates, same as e.g. ITK, SimpleITK and ITKSnap. I just committed the conversion script that we used for creating the csv files.
