### ISSUE TITLE
New Release SimpleITK 2.0.0 incompatible with tensorflow 1.14

### ISSUE THREAD

**Issue by miruna20** [christianpayer/MedicalDataAugmentationTool-VerSe#8]
10 days ago a new version of SimpleITK (2.0.0) has been released. This is incompatible with TensorFlow 1.14, the base docker container for inference, and results in a Segmentation Fault when running main_spine_localization.py

**Comment by lpengc** [comment]
SimpleITK's Version goes back to 1.2.4 is OK.

**Comment by christianpayer** [comment]
I committed some changes that should make the framework work with SimpleITK 2 and above. However, I did not test it extensively, so if you encounter problems with SimpleITK 2, downgrade to 1.2.4.
